version: "3.7"
services:
  matsher:
    image: matsher-dev-api
    container_name: matsher-dev-api
    build:
      context: .
      args:
        - PORT = ${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - matsher-nw
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
  mongo:
    image: mongo:7.0
    container_name: matsher-dev-db
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    networks:
      - matsher-nw
    volumes:
      - mongo-data:/data/db

networks:
  matsher-nw:
    driver: bridge

volumes:
  mongo-data:
    driver: local
